Repository AY2021S1-CS2103-F09-3/tp, pull requests merged in 2020-10, with the labels that each got.

#74 Tutorial 3 - Adding a new Command (Do not merge)
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/RemarkCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Remark.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/model/person/RemarkTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: good first issue, priority.Low

#73 Add times command to the project
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TimesCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/TimesCommandParser.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Times.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/TimesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TimesCommandParserTest.java
  src/test/java/seedu/address/model/person/TimesTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Implementation

#78 Branch update author
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TimesCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Author.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Implementation

#82 Caiyi34777 category implementation
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/Gemfile.lock
  docs/UserGuide.md
  docs/_sass/minima/skins/classic.scss
  docs/_sass/minima/skins/solarized.scss
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/tutorials/AddRemark.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TimesCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/category/Category.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tag/Tag.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedCategory.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedTag.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ArgumentTokenizerTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/category/CategoryTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/model/tag/TagTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: priority.High, type.Implementation

#83 Caiyi34777 category implementation update
  docs/Gemfile.lock
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
Labels: priority.High, type.Implementation

#80 Implement the location and stocking
  docs/team/hcy123902.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/commands/TimesCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/StockCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/NumberContainsKeywordPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Stocking.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedStocking.java
  src/main/java/seedu/address/ui/LibraryBookDetailCard.java
  src/main/java/seedu/address/ui/Mode.java
  src/main/java/seedu/address/ui/PersonListPanel.java
  src/main/resources/view/LibraryBookDetailCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/StockCommandTest.java
  src/test/java/seedu/address/logic/parser/StockCommandParserTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/NumberContainsKeywordPredicateTest.java
  src/test/java/seedu/address/model/person/StockingTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Implementation

#87 Implement the location
  src/main/java/seedu/address/logic/commands/StockCommand.java
Labels: type.Implementation

#90 Implement deleteBy ISBN or times and add tests
  src/main/java/seedu/address/logic/commands/DeleteByCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteByCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteByNameCommandParser.java
  src/test/java/seedu/address/logic/commands/DeleteByCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteByCommandParserTest.java
Labels: type.Implementation

#91 Update the sample data
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalBookAddressBook.json
Labels: priority.Medium, type.Implementation

#92 Fixed bugs regarding the edit command
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/book/Times.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/TimesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/TimesCommandParserTest.java
  src/test/java/seedu/address/model/book/TimesTest.java
Labels: priority.High, type.Implementation

#93 Update edit command
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/model/book/Times.java
  src/test/java/seedu/address/logic/commands/EditBookDescriptorTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/testutil/EditBookDescriptorBuilder.java
Labels: priority.High, type.Implementation

#96 Add change to the command
  src/main/java/seedu/address/storage/JsonAdaptedStocking.java
Labels: priority.Medium, type.Implementation

#100 Modify the version of MainApp
  src/main/java/seedu/address/MainApp.java
Labels: priority.Low, type.Implementation

#104 History command implementation
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/HistoryCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/book/Times.java
Labels: priority.High, type.Implementation

#106 Usage command implementation
  config/checkstyle/checkstyle.xml
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteByCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/commands/UsageByCommand.java
  src/main/java/seedu/address/logic/commands/UsageCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/UsageByCommandParser.java
  src/main/java/seedu/address/logic/parser/UsageCommandParser.java
  src/main/java/seedu/address/model/book/NumberContainsKeywordPredicate.java
  src/main/java/seedu/address/ui/BookListPanel.java
Labels: priority.High, type.Implementation

#109 Maintain the defensiveness
  build.gradle
  src/main/java/seedu/address/ui/BookCardWithCover.java
  src/main/java/seedu/address/ui/BookCoverManager.java
Labels: type.Implementation

#111 Add implementation documentation to the Developer Guide
  docs/DeveloperGuide.md
  docs/diagrams/AddStockingParserSequenceDiagram.puml
  docs/diagrams/AddStockingSequenceDiagram.puml
  docs/diagrams/ModelClassBookStockingDiagram.puml
  docs/diagrams/StockCommandParserSequenceDiagram.puml
  docs/diagrams/StockCommandSequenceDiagram.puml
  docs/images/AddStockingParserSequenceDiagram.png
  docs/images/AddStockingSequenceDiagram.png
  docs/images/AddStockingSequenceDiagram1.png
  docs/images/ModelClassBookStockingDiagram.png
  docs/images/StockCommandParserSequenceDiagram.png
  docs/images/StockCommandSequenceDiagram.png
Labels: type.Documentation

#119 Update developer guide
  docs/DeveloperGuide.md
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteBySequenceDiagram.png
Labels: type.Documentation

#130 Update the landing page to mid-v1.3
  docs/images/Ui.png
  docs/index.md
Labels: priority.Medium, type.Documentation

#131 Updated the UG
  docs/UserGuide.md
Labels: priority.High, type.Documentation

#124 Branch add problem
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddProblemCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ViewProblemCommand.java
  src/main/java/seedu/address/logic/parser/AddProblemCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/Library.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/Problem/Description.java
  src/main/java/seedu/address/model/Problem/Problem.java
  src/main/java/seedu/address/model/Problem/ProblemList.java
  src/main/java/seedu/address/model/Problem/Severity.java
  src/main/java/seedu/address/model/ReadOnlyLibrary.java
  src/main/java/seedu/address/storage/JsonAdaptedProblem.java
  src/main/java/seedu/address/storage/JsonSerializableLibrary.java
  src/main/java/seedu/address/storage/StorageForProblem.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
Labels: type.Implementation

#141 Branch fix view problem command storage
  src/main/java/seedu/address/logic/commands/ViewProblemCommand.java
  src/main/java/seedu/address/model/Library.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/problem/ProblemList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug, priority.High, type.Implementation

#142 Branch update ug add problem view problem
  docs/UserGuide.md
Labels: documentation, priority.High, type.Documentation

#143 Update UI
  README.md
  src/main/java/seedu/address/ui/BookCardWithCover.java
  src/main/java/seedu/address/ui/LibraryBookDetailCard.java
  src/main/java/seedu/address/ui/LibraryBookDetailReviewCard.java
  src/main/java/seedu/address/ui/UiManager.java
  src/main/resources/view/Base.css
  src/main/resources/view/ColourTheme.css
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High, type.Implementation

#145 Add command description in the User Guide
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/SearchReviewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/parser/AddReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/SearchReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/StockCommandParser.java
  src/test/data/JsonSerializableLibraryTest/typicalBookLibrary.json
Labels: type.Documentation

#147 Branch ug update
  docs/UserGuide.md
Labels: priority.High, type.Documentation, type.UserGuide

#149 Add the command description in the Developer Guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/SearchReviewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/model/review/Rating.java
  src/main/java/seedu/address/model/review/Review.java
  src/main/java/seedu/address/model/review/ReviewContent.java
  src/main/java/seedu/address/model/review/ReviewNumber.java
  src/main/java/seedu/address/ui/BookCardWithCover.java
  src/main/java/seedu/address/ui/BookCoverManager.java
  src/main/java/seedu/address/ui/BookListPanel.java
  src/main/java/seedu/address/ui/BookReviewCard.java
  src/main/java/seedu/address/ui/LibraryBookDetailReviewCard.java
  src/main/java/seedu/address/ui/LibraryBookDetailStockingCard.java
  src/main/resources/view/LibraryBookDetailStockingCard.fxml
Labels: type.Documentation

#151 Add the command information to Developer Guide
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/SearchReviewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/book/Stocking.java
  src/main/java/seedu/address/model/review/ReviewContent.java
  src/main/java/seedu/address/model/review/ReviewNumber.java
  src/test/java/seedu/address/model/book/StockingTest.java
Labels: type.Documentation

#153 Branch dg update
  docs/UserGuide.md
  docs/diagrams/DeleteBySequenceDiagram.puml
  docs/diagrams/DeleteSequenceDiagram.puml
  docs/images/DeleteBySequenceDiagram.png
Labels: priority.High, type.DeveloperGuide, type.Documentation, type.UserGuide

#154 V1.3 DG davidsqf
  docs/DeveloperGuide.md
  docs/diagrams/AddProblemSequenceDiagram.puml
  docs/images/AddProblemSequenceDiagram.png
Labels: documentation, priority.High, type.DeveloperGuide, type.Documentation

#156 Minor fix on find problem report
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindProblemReportCommand.java
  src/main/java/seedu/address/logic/parser/FindProblemReportCommandParser.java
Labels: priority.High, type.Implementation

#158 Implement the documentation
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/book/Stocking.java
  src/main/java/seedu/address/ui/LibraryBookDetailStockingCard.java
Labels: type.Documentation
