Repository AY2021S1-CS2103-F09-3/tp, pull requests merged in 2020-11, with the labels that each got.

#213 Update the review
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteProblemCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/Stocking.java
  src/main/java/seedu/address/model/review/ReviewContent.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedBook.java
  src/main/java/seedu/address/storage/JsonAdaptedStocking.java
  src/main/java/seedu/address/ui/BookCoverManager.java
  src/main/java/seedu/address/ui/LibraryBookDetailReviewCard.java
  src/main/java/seedu/address/ui/LibraryBookDetailStockingCard.java
  src/main/resources/view/LibraryBookDetailReviewCard.fxml
  src/test/data/JsonSerializableLibraryTest/typicalBookLibrary.json
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/book/StockingTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
Labels: type.Documentation, type.Implementation, type.UserGuide

#222 Implement UI for pr and fix previous UI bugs
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindProblemReportCommand.java
  src/main/java/seedu/address/logic/commands/ViewProblemCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ProblemReportListCard.java
  src/main/java/seedu/address/ui/ProblemReportListPanel.java
  src/main/resources/view/BookListCardWithCover.fxml
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProblemReportListCard.fxml
  src/main/resources/view/ProblemReportListPanel.fxml
Labels: priority.High, type.Implementation

#223 Fixed bugs
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/model/book/Times.java
  src/main/resources/view/BookListCardWithCover.fxml
Labels: priority.High, type.Implementation

#224 Fix sizing bug in pr UI
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ProblemReportListCard.fxml
Labels: priority.High, type.Implementation

#226 Fixes
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/resources/view/DarkTheme.css
Labels: priority.High, type.Implementation

#231 Add the edit review command
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/logic/commands/SearchReviewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/parser/AddReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/DeleteReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/EditReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
  src/main/java/seedu/address/ui/LibraryBookDetailReviewCard.java
  src/main/resources/view/BookReviewCard.fxml
Labels: type.Implementation

#227 handle invalid command like "report problem/"
  src/main/java/seedu/address/logic/commands/AddProblemCommand.java
  src/main/java/seedu/address/logic/commands/ViewProblemCommand.java
  src/main/java/seedu/address/logic/parser/AddProblemCommandParser.java
  src/main/java/seedu/address/model/problem/Description.java
Labels: bug, priority.High, type.Implementation

#232 add ReportProblem and ViewProblem in command summary
  docs/UserGuide.md
Labels: documentation, priority.High, type.Documentation

#233 add section of ViewProblemCommand
  docs/DeveloperGuide.md
  docs/diagrams/ViewProblemSequenceDiagram.puml
  docs/images/ViewProblemSequenceDiagram.png
Labels: documentation, priority.High, type.Documentation

#237 Update the review
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/intellibrary/model/review/ReviewContent.java
  src/main/resources/view/LibraryBookDetailStockingCard.fxml
Labels: priority.High, type.Documentation, type.Implementation

#235 update project-portfolio-page of davidsqf
  docs/diagrams/ViewProblemSequenceDiagram.puml
  docs/images/ViewProblemSequenceDiagram.png
  docs/team/davidsqf.md
Labels: documentation, priority.Medium, type.Documentation

#239 Code quality
  src/main/java/seedu/intellibrary/model/problem/Description.java
  src/main/java/seedu/intellibrary/model/problem/Severity.java
  src/test/java/seedu/intellibrary/model/problem/DescriptionTest.java
  src/test/java/seedu/intellibrary/model/problem/ProblemTest.java
  src/test/java/seedu/intellibrary/model/problem/SeverityTest.java
Labels: priority.High, type.Implementation

#241 Update davidsqf.md
  docs/team/davidsqf.md
Labels: documentation, priority.High, type.Documentation

#242 add test code for three models: Severity, Description, and Problem
  src/test/java/seedu/address/model/problem/DescriptionTest.java
  src/test/java/seedu/address/model/problem/ProblemTest.java
  src/test/java/seedu/address/model/problem/SeverityTest.java
Labels: priority.Medium, type.Implementation

#244 Update the review
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/model/review/ReviewContent.java
  src/main/resources/view/LibraryBookDetailStockingCard.fxml
Labels: priority.High, type.Documentation, type.Implementation

#245 delete redundant stuff
  docs/team/davidsqf.md
Labels: documentation, priority.Medium, type.AboutUs, type.Documentation

#249 update Ui.png
  docs/images/Ui.png
Labels: priority.High, type.ReadMe

#250 Branch ppp siyuan
  docs/AboutUs.md
  docs/team/Stefan-Jiang.md
  docs/team/stefan-jiang.md
  git
Labels: documentation, priority.High

#253 Update the content of the project portfolio page
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/images/explanation/explanation.jpg
  docs/team/hcy123902.md
Labels: priority.High, type.Documentation

#255 Implement the changing of content
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/test/java/seedu/address/logic/commands/StockCommandTest.java
  src/test/java/seedu/address/logic/parser/AddReviewCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StockCommandParserTest.java
Labels: priority.High, type.Implementation

#256 V1.4 DG
  docs/DeveloperGuide.md
Labels: documentation, priority.High, type.DeveloperGuide

#257 fix major bug: duplicate problem not detected
  src/main/java/seedu/address/model/Library.java
  src/main/java/seedu/address/model/problem/Description.java
  src/main/java/seedu/address/model/problem/Problem.java
  src/main/java/seedu/address/model/problem/ProblemList.java
  src/main/java/seedu/address/model/problem/Severity.java
  src/main/java/seedu/address/model/problem/exceptions/DuplicateProblemException.java
Labels: bug, priority.High, type.Implementation

#258 add rationale for rejecting duplicate problem
  docs/UserGuide.md
Labels: documentation, priority.Medium, type.UserGuide

#261 Fixed some UI issues
  docs/UserGuide.md
  docs/team/stefan-jiang.md
Labels: priority.High, type.Documentation

#265 Update the Developer Guide
  docs/DeveloperGuide.md
  docs/team/hcy123902.md
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/logic/commands/SearchReviewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/model/review/Rating.java
  src/main/java/seedu/address/model/review/Review.java
  src/main/java/seedu/address/model/review/ReviewContent.java
  src/main/java/seedu/address/model/review/ReviewNumber.java
  src/test/java/seedu/address/logic/commands/StockCommandTest.java
  src/test/java/seedu/address/logic/parser/StockCommandParserTest.java
Labels: type.DeveloperGuide, type.Documentation, type.UserGuide

#266 Update the documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/hcy123902.md
Labels: priority.High, type.DeveloperGuide, type.Documentation

#267 Update the documentation
  docs/DeveloperGuide.md
  docs/team/hcy123902.md
Labels: priority.High, type.DeveloperGuide, type.Documentation

#268 Update UG and fixed Edit Command issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/TimesCommand.java
  src/main/java/seedu/address/model/book/Book.java
Labels: documentation, priority.High, type.Implementation

#269 Update the documentation
  docs/images/explanation/explanation.jpg
  docs/team/hcy123902.md
  src/main/resources/images/library_32.png
Labels: priority.High, type.DeveloperGuide, type.Documentation

#271 Final push for UG
  docs/UserGuide.md
Labels: documentation, priority.High

#270 Update the documentation
  docs/UserGuide.md
  docs/team/hcy123902.md
Labels: priority.High, type.DeveloperGuide, type.Documentation

#273 Improve code quality of random command
  src/main/java/seedu/address/logic/commands/RandomCommand.java
Labels: type.Implementation

#274 Improve code quality of findMax times command
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/FindMostPopularCommand.java
  src/main/java/seedu/address/logic/commands/RandomCommand.java
  src/main/java/seedu/address/logic/commands/SortCommand.java
  src/main/java/seedu/address/logic/parser/FindMostPopularCommandParser.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
  src/main/java/seedu/address/logic/parser/SortCommandParser.java
Labels: priority.High, type.Implementation

#275 add test code for AddProblemCommand and ViewProblemCommand
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/problem/Description.java
  src/main/java/seedu/address/model/problem/Problem.java
  src/main/java/seedu/address/model/problem/ProblemList.java
  src/main/java/seedu/address/model/problem/Severity.java
  src/test/java/seedu/address/logic/commands/AddProblemCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/ViewProblemCommandTest.java
  src/test/java/seedu/address/testutil/ProblemBuilder.java
  src/test/java/seedu/address/testutil/TypicalProblems.java
Labels: priority.Medium, type.Implementation

#276 Branch add tests
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/DeleteProblemCommand.java
  src/main/java/seedu/address/logic/commands/FindProblemCommand.java
  src/main/java/seedu/address/logic/parser/DeleteProblemCommandParser.java
  src/main/java/seedu/address/logic/parser/FindProblemCommandParser.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
  src/main/java/seedu/address/ui/ProblemReportListCard.java
  src/test/java/seedu/address/logic/commands/FindProblemCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteProblemCommandParserTest.java
  src/test/java/seedu/address/logic/parser/FindProblemCommandParserTest.java
Labels: priority.Medium, type.Implementation

#277 Fix incorrect delete problem message
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/DeleteProblemCommand.java
Labels: priority.High, type.Implementation

#279 Update the command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddCommand.java
Labels: priority.High, type.Documentation, type.Implementation

#282 Update davidsqf.md
  docs/team/davidsqf.md
Labels: documentation, priority.High, type.Documentation

#283 update davidsqf.md
  docs/team/davidsqf.md
Labels: documentation, priority.High, type.Documentation

#285 Update some new features in PPP
  docs/team/richardcom.md
Labels: priority.Medium, type.Documentation

#290 Fix GUI errors
  docs/UserGuide.md
  src/main/resources/view/MainWindow.fxml
Labels: priority.Medium, type.Implementation

#293 add sample Problems to SampleDataUtil
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High

#296 change reportPr command syntax
  src/main/java/seedu/address/logic/commands/AddProblemCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
Labels: priority.Medium, type.Implementation

#299 Update UserGuide.md
  docs/UserGuide.md
Labels: documentation, priority.High, type.UserGuide

#300 V1.4 DG: update DG and sequence diagram of reportPr
  docs/DeveloperGuide.md
  docs/diagrams/AddProblemSequenceDiagram.puml
  docs/images/AddProblemSequenceDiagram.png
Labels: documentation, priority.High, type.DeveloperGuide

#303 Branch ugupdate
  docs/UserGuide.md
Labels: priority.High, type.UserGuide

#304 Branch info
  src/main/java/seedu/address/logic/commands/DeleteByCommand.java
  src/main/java/seedu/address/model/book/Book.java
Labels: priority.High, type.Implementation

#306 Implement Edit Problem Report command
  src/main/java/seedu/address/logic/commands/EditProblemCommand.java
  src/main/java/seedu/address/logic/parser/EditProblemCommandParser.java
  src/main/java/seedu/address/logic/parser/LibraryParser.java
Labels: priority.Medium, type.Implementation

#309 Update User Guide
  docs/UserGuide.md
Labels: priority.High, type.Documentation, type.UserGuide

#308 Update the command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/book/Stocking.java
  src/main/java/seedu/address/storage/JsonAdaptedReview.java
Labels: priority.High, type.Documentation, type.Implementation

#310 Update the tests
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditBookDescriptorTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/StockCommandTest.java
  src/test/java/seedu/address/logic/commands/TimesCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteByCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/StockCommandParserTest.java
  src/test/java/seedu/address/model/LibraryTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/book/BookTest.java
  src/test/java/seedu/address/model/book/UniqueBookListTest.java
  src/test/java/seedu/address/storage/JsonAdaptedBookTest.java
  src/test/java/seedu/address/storage/JsonLibraryStorageTest.java
  src/test/java/seedu/address/storage/JsonSerializableLibraryTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/BookBuilder.java
  src/test/java/seedu/address/testutil/TypicalBooks.java
Labels: priority.Medium, type.Implementation

#311 Final Push
  docs/UserGuide.md
  docs/team/stefan-jiang.md
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Documentation, type.Implementation

#312 Branch final ug
  docs/UserGuide.md
  src/main/resources/images/add_command.png
  src/main/resources/images/findReport.png
Labels: priority.High, type.UserGuide

#313 Fix bugs in UG
  docs/UserGuide.md
  docs/images/add_command.png
  docs/images/findReport.png
Labels: priority.Medium, type.Documentation, type.UserGuide

#315 Update the command
  docs/UserGuide.md
  docs/images/searchReviewCommandUserInterface.png
  docs/images/stockCommandUserInterface.png
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/book/Stocking.java
Labels: priority.High, type.Documentation, type.Implementation

#316 Finalize User Guide
  docs/UserGuide.md
Labels: priority.High, type.UserGuide

#318 Fix method on how to identify same book
  docs/UserGuide.md
  src/main/java/seedu/address/model/book/Book.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
Labels: priority.High, type.Implementation

#320 Update the documentation
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/SearchReviewCommand.java
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/main/java/seedu/address/logic/parser/SearchReviewCommandParser.java
  src/main/java/seedu/address/logic/parser/StockCommandParser.java
  src/test/java/seedu/address/logic/commands/StockCommandTest.java
Labels: priority.High, type.Documentation

#324 New code quality
  docs/UserGuide.md
  src/main/java/seedu/address/logic/LogicManager.java
Labels: documentation, priority.High

#325 Update developer guide
  AddCommandSequenceDiagram.png
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddCommandSequenceDiagram.puml
  docs/diagrams/EditProblemReportSequenceDiagram.puml
  docs/diagrams/FindProblemReportSequenceDiagram.puml
  docs/diagrams/findMostPopularSequenceDiagram.puml
  docs/diagrams/randomCommandSequenceDiagram.puml
  docs/images/AddCommandSequenceDiagram.png
  docs/images/EditProblemReportSequenceDiagram.png
  docs/images/FindProblemReportSequenceDiagram.png
  docs/images/findMostPopularSequenceDiagram.png
  docs/images/randomCommandSequenceDiagram.png
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
Labels: priority.High, type.DeveloperGuide

#327 modify ReportProblem sequence diagram
  docs/diagrams/AddProblemSequenceDiagram.puml
  docs/images/AddProblemSequenceDiagram.png
Labels: documentation, priority.High, type.DeveloperGuide

#329 change self photo
  docs/images/davidsqf.png
Labels: priority.Low

#328 Update the documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddReviewParserSequenceDiagram.puml
  docs/diagrams/AddStockingParserSequenceDiagram.puml
  docs/diagrams/AddStockingSequenceDiagram.puml
  docs/diagrams/EditStockingParserSequenceDiagram.puml
  docs/diagrams/ModelClassBookReviewDiagram.puml
  docs/diagrams/ModelClassBookStockingDiagram.puml
  docs/diagrams/StockCommandParserSequenceDiagram.puml
  docs/diagrams/StockCommandSequenceDiagram.puml
  docs/images/AddReviewParserSequenceDiagram.png
  docs/images/EditStockingParserSequenceDiagram.png
  docs/images/ModelClassBookReviewDiagram.png
  docs/images/StockCommandParserSequenceDiagram.png
  docs/images/searchReviewCommandUserInterface.png
  docs/team/hcy123902.md
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/ui/BookReviewCard.java
Labels: priority.High, type.Documentation

#330 Update davidsqf.md
  docs/team/davidsqf.md
Labels: documentation, priority.Medium, type.AboutUs

#333 update Ui.png
  docs/images/Ui.png
Labels: documentation, priority.High, type.UserGuide

#339 Tutorial adding command
  src/main/java/seedu/address/logic/commands/EmptyCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
Labels: good first issue

#340 Update the documentation
  docs/team/hcy123902.md
Labels: priority.Medium, type.Documentation

#341 Update DG
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/team/stefan-jiang.md
Labels: documentation, priority.Medium

#342 Update PPP
  docs/team/stefan-jiang.md
Labels: priority.Low

#343 Update again again
  docs/team/stefan-jiang.md
Labels: priority.Low

#344 Update the implementation
  docs/DeveloperGuide.md
  src/main/java/seedu/address/ui/LibraryBookDetailReviewCard.java
  src/main/resources/view/Base.css
  src/main/resources/view/LibraryBookDetailReviewCard.fxml
Labels: priority.High, type.Implementation

#346 Footer update
  .gitignore
  docs/DeveloperGuide.md
  docs/tutorials/AddRemark.md
  docs/tutorials/RemovingFields.md
  docs/tutorials/TracingCode.md
  src/main/java/seedu/address/commons/core/Config.java
  src/main/java/seedu/address/storage/JsonAdaptedProblem.java
  src/main/java/seedu/address/storage/StorageForProblem.java
  src/test/data/ConfigUtilTest/ExtraValuesConfig.json
  src/test/data/ConfigUtilTest/TypicalConfig.json
  src/test/data/JsonUserPrefsStorageTest/ExtraValuesUserPref.json
  src/test/java/seedu/address/commons/core/ConfigTest.java
  src/test/java/seedu/address/commons/util/ConfigUtilTest.java
Labels: enhancement, priority.Medium

#348 gitignore
  .gitignore
  config/footer/config.json
  config/footer/preferences.json
Labels: duplicate

#349 storage diagram
  docs/diagrams/StorageClassDiagram.puml
Labels: duplicate

#347 Update the Developer Guide
  config/footer/config.json
  docs/DeveloperGuide.md
  docs/team/hcy123902.md
  src/test/java/seedu/address/commons/core/ConfigTest.java
Labels: priority.High, type.Documentation

#353 Update the documentation
  docs/team/hcy123902.md
Labels: priority.High, type.Documentation

#357 Update the documentation
  docs/team/hcy123902.md
Labels: priority.High, type.Documentation

#360 Update the documentation
  docs/DeveloperGuide.md
  docs/UserGuide.md
  preferences.json
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
Labels: priority.High, type.Documentation

#362 Update the command
  src/main/java/seedu/address/logic/commands/StockCommand.java
  src/test/java/seedu/address/logic/commands/StockCommandTest.java
  src/test/java/seedu/address/logic/parser/StockCommandParserTest.java
  src/test/java/seedu/address/model/review/RatingTest.java
  src/test/java/seedu/address/model/review/ReviewContentTest.java
  src/test/java/seedu/address/model/review/ReviewNumberTest.java
Labels: priority.High, type.Implementation

#364 user stories format
  docs/DeveloperGuide.md
  docs/images/StorageClassDiagram.png
Labels: documentation, enhancement, priority.High

#369 Final Tweak
  docs/DeveloperGuide.md
  preferences.json
Labels: priority.Low

#370 V1.4 DG
  docs/DeveloperGuide.md
  docs/images/ModelClassDiagram.png
Labels: documentation, priority.High, type.DeveloperGuide

#371 Update the documentation
  docs/team/hcy123902.md
Labels: priority.High, type.Documentation

#372 Update the documentation
  docs/team/hcy123902.md
Labels: priority.High, type.Documentation

#373 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: documentation, priority.High, type.DeveloperGuide

#380 Update the documentation
  .gitignore
  config.json
  docs/DeveloperGuide.md
  docs/UserGuide.md
  preferences.json
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
  src/main/java/seedu/address/ui/BookCoverManager.java
Labels: priority.High, type.Documentation

#382 Update the documentation
  .gitignore
  preferences.json
Labels: priority.High, type.Documentation

#386 Update the documentation
  config.json
  docs/UserGuide.md
  preferences.json
Labels: priority.High, type.Documentation

#400 Update the documentation
  preferences.json
  src/main/java/seedu/address/logic/commands/AddReviewCommand.java
  src/main/java/seedu/address/logic/commands/DeleteReviewCommand.java
  src/main/java/seedu/address/logic/commands/EditReviewCommand.java
Labels: priority.High, type.Documentation

#411 Update the documentation
  docs/DeveloperGuide.md
  docs/images/EditStockingParserSequenceDiagram.png
Labels: priority.High, type.Documentation

#414 Update the documentation
  docs/DeveloperGuide.md
  preferences.json
Labels: priority.High, type.Documentation
